name: CI
on:
  release:
    types: [published, edited, prereleased]

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/build.yml
